repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: yamllint
        name: Validate YAML files
        entry: uv run yamllint
        language: system
        types: [yaml]
        files: ^rules/.*\.ya?ml$

      - id: validate-sigma-schema
        name: Validate Sigma schema
        entry: uv run sigma check rules/
        language: system
        pass_filenames: false
        files: ^rules/.*\.ya?ml$
