[project]
name = "detections-as-code-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pysigma-backend-crowdstrike==3.0.0",
    "pysigma-backend-kusto==1.0.1",
    "sigma-cli==3.0.3",
    "yamllint==1.38.0",
]

[dependency-group]
dev = [
    "pre-commit>=3.0"
]
